stages:
  make:
    cmd: poetry run make-dataset --reprocess True
    deps:
    - data/Asteroid.csv
    - src/asteroid_diameter_prediction/train/make_dataset.py
    params:
    - make.vif_threshold
    outs:
    - data/Asteroid_processed.csv

  enrich:
    cmd: poetry run enrich-features --reprocess True
    deps:
    - data/Asteroid_processed.csv
    - src/asteroid_diameter_prediction/train/enrich_features.py
    params:
    - enrich.log_features
    outs:
    - data/Asteroid_enriched.csv

  train:
    cmd: poetry run train-model
    deps:
    - data/Asteroid_enriched.csv
    - src/asteroid_diameter_prediction/train/train_model.py
    params:
    - train.seed
    - train.split
    outs:
    - models/diameter_prediction_model.joblib

metrics:
- dvclive/metrics.json
plots:
- column vs coef:
    template: simple
    x: column
    y:
      dvclive/plots/custom/Coefficient_values.json: coef

- dvclive/plots/metrics:
    x: step
- dvclive/plots/images
- dvclive/plots/custom/Coefficient_values.json:
    template: bar_horizontal
    x: coef
    y: column
    title: Coefficient values for Asteroid diameter prediction
    x_label: Feature
    y_label: Coefficient value
